/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

/**
 *
 * @author Arimbi
 */
import Menu.Tugas;
import Menu.konek;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import View.Login;


public class tmpltugas extends javax.swing.JFrame {

    /**
     * Creates new form tmpltugas
     */
    String Username;
    private void search(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No.");
        model.addColumn("Nama Tugas");
        model.addColumn("Mata Kuliah");
        model.addColumn("Hari Pengumpulan");
        model.addColumn("Deadline");
        
        try{
            String sql = "SELECT * FROM tugas WHERE waktu_pengumpulan LIKE ('"+txtdeadline.getText()+"')";
            java.sql.Connection con = (Connection)konek.konekDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            tbltugas.setModel(model);
            }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
            }
    }
    private void tampiltbl(){
       DefaultTableModel model = new DefaultTableModel();
       model.addColumn("No.");
       model.addColumn("Nama Tugas");
       model.addColumn("Mata Kuliah");
       model.addColumn("Hari Pengumpulan");
       model.addColumn("Deadline");
       
       try{
       
           String sql = "SELECT * FROM tugas WHERE username ='"+Username+"'";
           java.sql.Connection con = (Connection)konek.konekDB();
           java.sql.Statement stm = con.createStatement();
           java.sql.ResultSet res = stm.executeQuery(sql);
           
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            tbltugas.setModel(model);
       }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
       }
    }
    public tmpltugas() {
        initComponents();
        search();
        tampiltbl();
    }
    public tmpltugas(String Username){
        initComponents();
        this.Username=Username;
        search();
        tampiltbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbltugas = new javax.swing.JTable();
        txtdeadline = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnall = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbltugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltugas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 930, 138));

        txtdeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeadlineActionPerformed(evt);
            }
        });
        getContentPane().add(txtdeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 173, -1));

        btnsearch.setBackground(new java.awt.Color(0, 153, 102));
        btnsearch.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnsearch.setText("search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        btnall.setBackground(new java.awt.Color(0, 153, 102));
        btnall.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnall.setText("show all");
        btnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallActionPerformed(evt);
            }
        });
        getContentPane().add(btnall, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        btnback.setBackground(new java.awt.Color(0, 153, 102));
        btnback.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btnback.setText("back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeadlineActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallActionPerformed
        // TODO add your handling code here:
        tampiltbl();
    }//GEN-LAST:event_btnallActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        dispose();
        Tugas n = new Tugas();
        n.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tmpltugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tmpltugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tmpltugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tmpltugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tmpltugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnall;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbltugas;
    private javax.swing.JTextField txtdeadline;
    // End of variables declaration//GEN-END:variables
}
