/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
//import Tampilan.MainMenu;



import View.MenuUtama;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arimbi
 */
public class Tugas extends javax.swing.JFrame {
     String Username;
       private void kosong(){
           txtNoTugas.setEditable(true);
           txtNoTugas.setText(null);
           txtNamaTugas.setText(null);
           txtMatkul.setText(null);
           cbHari.setSelectedItem(this);
           txtWaktu.setText(null);
           
       }
      /* private void tampilkan_data(){
           DefaultTableModel model = new DefaultTableModel(); 
           model.addColumn("No.");
           model.addColumn("Nama Tugas");
           model.addColumn("Nama Matkul");
           model.addColumn("Hari");
           model.addColumn("Waktu pengumpulan");
           
        try{
            String sql = "select * from tugas";
            java.sql.Connection con = (Connection)konek.konekDB();
            java.sql.Statement stm = con.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[] {res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5)});   
            }
            tugas.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : " + e.getMessage());
        }

    }
    /**
     * Creates new form Tugas
     */
    public Tugas() {
        initComponents();
        kosong();
    }
      public String getUsername() {
        return Username;
    }
    public Tugas(String Username){
        initComponents();
        kosong();
        this.Username=Username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        NoTugas = new javax.swing.JLabel();
        NamaTugas = new javax.swing.JLabel();
        Matkul = new javax.swing.JLabel();
        Hari = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        btClear = new javax.swing.JButton();
        btShow = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btinsert = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        txtNoTugas = new javax.swing.JTextField();
        txtNamaTugas = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        cbHari = new javax.swing.JComboBox();
        txtWaktu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btsearch = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi");
        setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("TUGAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 11, -1, -1));

        NoTugas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        NoTugas.setText("No tugas");
        getContentPane().add(NoTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        NamaTugas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        NamaTugas.setText("Nama tugas");
        getContentPane().add(NamaTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        Matkul.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Matkul.setText("Nama Matakuliah");
        getContentPane().add(Matkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        Hari.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Hari.setText("Hari Pengumpulan");
        getContentPane().add(Hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        Waktu.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        Waktu.setText("Waktu Pengumpulan");
        getContentPane().add(Waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        btClear.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btClear.setText("Clear");
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        btShow.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btShow.setText("Show");
        btShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowActionPerformed(evt);
            }
        });
        getContentPane().add(btShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        btUpdate.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btUpdate.setText("Update");
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        btinsert.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btinsert.setText("Insert");
        btinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertActionPerformed(evt);
            }
        });
        getContentPane().add(btinsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        btDelete.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        txtNoTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTugasActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 218, -1));
        getContentPane().add(txtNamaTugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 218, -1));
        getContentPane().add(txtMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 218, -1));

        cbHari.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        cbHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SENIN", "SELASA", "RABU", "KAMIS", "JUMAT", "SABTU", "MINGGU" }));
        getContentPane().add(cbHari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 110, -1));

        txtWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWaktuActionPerformed(evt);
            }
        });
        getContentPane().add(txtWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 218, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*Tahun-Bulan-Tanggal Jam:Menit:Detik");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 218, -1));

        btsearch.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        btsearch.setText("Search");
        btsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        btnexit.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btnexit.setText("Back to menu");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        getContentPane().add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Delete FROM tugas WHERE no_tugas='"+txtNoTugas.getText()+"'";
            java.sql.Connection conn = (Connection)konek.konekDB();
            java.sql.PreparedStatement pstm= conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil!!");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO tugas VALUES ('"+txtNoTugas.getText()+
                    "','"+txtNamaTugas.getText()+"','"+txtMatkul.getText()+
                    "','"+cbHari.getSelectedItem()+"','"+txtWaktu.getText()+
                    "','"+getUsername()+"')";
            
            java.sql.Connection con = (Connection)konek.konekDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses simpan data berhasil..");
            kosong();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btinsertActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE tugas SET no_tugas='"+txtNoTugas.getText()+
                    "',nama_tugas='"+txtNamaTugas.getText()+
                    "',mata_kuliah='"+txtMatkul.getText()+
                    "',hari_pengumpulan='"+cbHari.getSelectedItem()+
                    "',waktu_pengumpulan='"+txtWaktu.getText()+
                    "' WHERE no_tugas = '"+txtNoTugas.getText()+"'";
            java.sql.Connection con = (Connection)konek.konekDB();
            java.sql.PreparedStatement pstm = con.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Proses update data berhasil..");
            
        }catch (HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
 //       tampil();
        kosong();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowActionPerformed
            dispose();
            tmpltugas n = new tmpltugas();
            n.setVisible(true);
    }//GEN-LAST:event_btShowActionPerformed

    private void txtWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWaktuActionPerformed

    private void txtNoTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTugasActionPerformed

    private void btsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsearchActionPerformed
        // TODO add your handling code here:
        Search n = new Search();
                n.setVisible(true);
                n.pack();
                n.setLocationRelativeTo(null);
                n.setExtendedState(MenuUtama.MAXIMIZED_HORIZ);
                
                this.dispose();
    }//GEN-LAST:event_btsearchActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_btClearActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        //        System.exit(0);
        dispose();
        MenuUtama n = new MenuUtama();
        n.setVisible(true);

    }//GEN-LAST:event_btnexitActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hari;
    private javax.swing.JLabel Matkul;
    private javax.swing.JLabel NamaTugas;
    private javax.swing.JLabel NoTugas;
    private javax.swing.JLabel Waktu;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btShow;
    private javax.swing.JButton btUpdate;
    private javax.swing.JButton btinsert;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btsearch;
    private javax.swing.JComboBox cbHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtNamaTugas;
    private javax.swing.JTextField txtNoTugas;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}